name: Pull Request
on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  NODE_VERSION: ${{ '18' }}

jobs:
  build:
    name: '🛠️ Build'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
